version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/app/config.yaml:ro
    networks:
      - network
    restart: unless-stopped
  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - network

  migrate:
    image: migrate/migrate:v4.16.2
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      until nc -z db 5432;
      do sleep 2; done;
      migrate -path=/migrations -database 'postgres://user:password@db:5432/db?sslmode=disable' up
      "

    volumes:
      - ./migrations:/migrations:ro
    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16