address: "0.0.0.0"
port: "8080"
dsn: "user=user password=password dbname=db host=127.0.0.1 port=5432 sslmode=disable"
log_level: debug
secret_key: "secret_key"
admin_token: "admin_token"
upload_path: "uploads"
